export class FlightdynamicListModel {
    /// <summary>
    /// 航班号
    /// </summary>
    FlightNumber: string
    /// <summary>
    /// 航班日期
    /// </summary>
    Date: string
    /// <summary>
    /// 出发地
    /// </summary>
    FromAirport: string
    FromAirportName: string
    /// <summary>
    /// 降落地
    /// </summary>
    ToAirport: string
    ToAirportName: string
    /// <summary>
    /// 出发航站楼
    /// </summary>
    FromTerminal: string
    /// <summary>
    /// 落地航站楼
    /// </summary>
    ToTerminal: string
    /// <summary>
    /// 计划起飞时间
    /// </summary>
    PlanTakeoffTime: string
    /// <summary>
    /// 计划降低时间
    /// </summary>
    PlanArrivalTime: string
    /// <summary>
    /// 实际起飞时间
    /// </summary>
    RealTakeoffTime: string
    /// <summary>
    /// 实际落地时间
    /// </summary>
    RealArrivalTime: string
    /// <summary>
    /// 预计起飞时间
    /// </summary>
    EstimateTakeoffTime: string
    /// <summary>
    /// 预计落地时间
    /// </summary>
    EstimateArrivalTime: string
    /// <summary>
    /// 取消时间
    /// </summary>
    CancelTime: string
    /// <summary>
    /// 航司代码
    /// </summary>
    AirlineCode: string
    /// <summary>
    /// 机型
    /// </summary>
    PlaneType: string
    /// <summary>
    /// 出发准点率
    /// </summary>
    TakeoffOntimeRate: string
    /// <summary>
    /// 预计飞行时长
    /// </summary>
    TotalFlyTime: string
    /// <summary>
    /// 登机口
    /// </summary>
    BoardingGate: string
    /// <summary>
    /// 行李转盘
    /// </summary>
    Carousel: string
    /// <summary>
    /// 航班状态
    /// </summary>
    FlightDynamicStatusType : string
    StatusName: string
    AddDay: string
}