export class AccountEntity {
  RouteId: string;
  /// <summary>
  /// 用户名
  /// </summary>
  Name: string;
  /// <summary>
  /// 密码
  /// </summary>
  Password: string;
  /// <summary>
  /// 支付密码
  /// </summary>
  Payword: string;
  /// <summary>
  /// 真实姓名
  /// </summary>
  RealName: string;
  /// <summary>
  /// 手机号码
  /// </summary>
  Mobile: string;
  /// <summary>
  /// 邮箱
  /// </summary>
  Email: string;
  /// <summary>
  /// 是否启用
  /// </summary>
  IsUsed: string;
  /// <summary>
  /// 是否激活手机
  /// </summary>
  IsActiveMobile: string;
  /// <summary>
  /// 是否激活邮箱
  /// </summary>
  IsActiveEmail: string;
  /// <summary>
  /// 是否实名
  /// </summary>
  IsReality: string;

  /// <summary>
  /// 是否启用
  /// </summary>
  IsUsedName: string;
  /// <summary>
  /// 是否激活手机
  /// </summary>
  IsActiveMobileName: string;

  /// <summary>
  /// 是否激活邮箱
  /// </summary>
  IsActiveEmailName: string;
  /// <summary>
  /// 是否激活邮箱
  /// </summary>
  IsRealityName: string;
  /// <summary>
  /// 得到加密密码
  /// </summary>
  /// <returns></returns>
  virtual: string;
}